In [2]:
import numpy as np
import time

In [6]:
#excution performance
size = 13_000_000

py_list = list(range(size))
start = time.time()
sq_list = [i**2 for i in py_list]
end = time.time()
print(f"py time : {end  -start }sec " )

np_arr = np.array(py_list)
start = time.time()
sq_list = np_arr **2
end = time.time()
print(f"np time : {end  -start }sec " )

py time : 2.2311367988586426sec 
np time : 0.3074679374694824sec 


In [13]:
# multi-dimension arrays
arr2D = np.array([[1,2,3,4],[2,8,7,6],[1,2,3,5]])
print(arr2D)

print(np.sum(arr2D))

column_sum = np.sum(arr2D, axis= 0)
print(column_sum)

row_sum = np.sum(arr2D, axis=1)
print(row_sum)

print(arr2D[0:2,1:2])

[[1 2 3 4]
 [2 8 7 6]
 [1 2 3 5]]
44
[ 4 12 13 15]
[10 23 11]
[[2]
 [8]]


In [25]:
#3D array
arr3D = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[7,8]]])
print(arr3D,arr3D.shape )

print(arr3D[1,2,1])

print(arr3D[:,0,:])#row 
print(arr3D[:,:,0])#column
arr3D[:,0,:]= 88 
print(arr3D)

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [7 8]]] (2, 3, 2)
8
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 7]]
[[[88 88]
  [ 2  3]
  [ 3  4]]

 [[88 88]
  [ 5  6]
  [ 7  8]]]
